-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 16:17:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Survey` (
  `idSurvey` INT NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idSurvey`),
  INDEX `fk_Survey_User_idx` (`User_idUser` ASC),
  UNIQUE INDEX `idSurvey_UNIQUE` (`idSurvey` ASC),
  CONSTRAINT `fk_Survey_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Choices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Choices` (
  `idChoices` INT NOT NULL,
  `choice` VARCHAR(140) NOT NULL,
  `Survey_idSurvey` INT NOT NULL,
  PRIMARY KEY (`idChoices`),
  INDEX `fk_Choices_Survey1_idx` (`Survey_idSurvey` ASC),
  UNIQUE INDEX `idChoices_UNIQUE` (`idChoices` ASC),
  CONSTRAINT `fk_Choices_Survey1`
    FOREIGN KEY (`Survey_idSurvey`)
    REFERENCES `mydb`.`Survey` (`idSurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Results` (
  `idresults` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Choices_idChoices` INT NOT NULL,
  PRIMARY KEY (`idresults`),
  INDEX `fk_results_User1_idx` (`User_idUser` ASC),
  INDEX `fk_results_Choices1_idx` (`Choices_idChoices` ASC),
  UNIQUE INDEX `idresults_UNIQUE` (`idresults` ASC),
  CONSTRAINT `fk_results_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_Choices1`
    FOREIGN KEY (`Choices_idChoices`)
    REFERENCES `mydb`.`Choices` (`idChoices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
